name: UnPublish NPM Package
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm unpublish noimap@1.0.0 --force
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}